### ISSUE TITLE
syntax error, unexpected ':', expecting ')'

### ISSUE THREAD

**Issue by djxiong** [stpl/systango_hrm#2]
when run : rake redmine:plugins NAME=systango_hrm RAILS_ENV=production --trace
error occur as following:

<pre>
rake aborted!
/var/www/redmine/plugins/systango_hrm/lib/tasks/rake_tasks.rake:15: syntax error, unexpected ':', expecting ')'
...pdate_attributes(leaves_taken: total_leave) rescue nil)
                              ^
/var/www/redmine/plugins/systango_hrm/lib/tasks/rake_tasks.rake:15: syntax error, unexpected ')', expecting kEND
/usr/local/lib/ruby/gems/1.8/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:245:in `load'
/usr/local/lib/ruby/gems/1.8/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:245:in `load'
/usr/local/lib/ruby/gems/1.8/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:236:in `load_dependency'
/usr/local/lib/ruby/gems/1.8/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:245:in `load'
/var/www/redmine/lib/tasks/redmine.rake:126
/var/www/redmine/lib/tasks/redmine.rake:126:in `each'
/var/www/redmine/lib/tasks/redmine.rake:126
/usr/local/lib/ruby/gems/1.8/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:245:in `load'
/usr/local/lib/ruby/gems/1.8/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:245:in `load'
/usr/local/lib/ruby/gems/1.8/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:236:in `load_dependency'
/usr/local/lib/ruby/gems/1.8/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:245:in `load'
/usr/local/lib/ruby/gems/1.8/gems/railties-3.2.13/lib/rails/engine.rb:425:in `load_tasks'
/usr/local/lib/ruby/gems/1.8/gems/railties-3.2.13/lib/rails/engine.rb:425:in `each'
/usr/local/lib/ruby/gems/1.8/gems/railties-3.2.13/lib/rails/engine.rb:425:in `load_tasks'
/usr/local/lib/ruby/gems/1.8/gems/railties-3.2.13/lib/rails/application.rb:145:in `load_tasks'
/usr/local/lib/ruby/gems/1.8/gems/railties-3.2.13/lib/rails/railtie/configurable.rb:30:in `send'
/usr/local/lib/ruby/gems/1.8/gems/railties-3.2.13/lib/rails/railtie/configurable.rb:30:in `method_missing'
/var/www/redmine/Rakefile:7
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/rake_module.rb:25:in `load'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/rake_module.rb:25:in `load_rakefile'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/application.rb:589:in `raw_load_rakefile'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/application.rb:89:in `load_rakefile'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/application.rb:160:in `standard_exception_handling'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/application.rb:88:in `load_rakefile'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/application.rb:72:in `run'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/application.rb:160:in `standard_exception_handling'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/application.rb:70:in `run'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/bin/rake:33
/usr/local/bin/rake:19:in `load'
/usr/local/bin/rake:19
</pre>

**Comment by stpl** [comment]
You are on old Ruby version. Plugin supports 1.9.2 and above. This issue exists with the older ruby versions. You can refer this http://stackoverflow.com/questions/7780240/syntax-error-unexpected-expecting-in-stripe-form-using-rails-3 .
